name: Run My C Program

on:
  push:
    branches: [ "master" ]

jobs:
  compile-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile C Code
      run: |
        gcc cproograming/coditional/print.c
        ./a.out